In [14]:
from snf import datasets
import numpy as np
import pandas as pd



In [ ]:
digits = datasets.load_digits()
digits.keys()

In [2]:
for arr in digits.data:
    print(arr.shape)

(600, 76)
(600, 240)
(600, 216)
(600, 47)


In [4]:
groups, samples = np.unique(digits.labels, return_counts=True)

In [7]:
for grp, count in zip(groups, samples):
    print('Group {:.0f}: {} samples'.format(grp, count))

Group 0: 200 samples
Group 1: 200 samples
Group 2: 200 samples


In [8]:
import snf
affinity_networks = snf.make_affinity(digits.data, metric='euclidean', K=20, mu=0.5)

In [52]:
chem =  np.array(pd.read_csv('chem_Jacarrd_sim.csv', header=-1))
enzyme =  np.array(pd.read_csv('enzyme_Jacarrd_sim.csv', header=-1))
# chem = array(chem,enzyme)
affinity_network = [chem,enzyme]

In [54]:
fused_network = snf.snf(affinity_network, K=20)

c:\program files\python36\lib\site-packages\snf\compute.py:401: RuntimeWarning: invalid value encountered in true_divide
  mat = mat / np.nansum(mat, axis=1, keepdims=True)
c:\program files\python36\lib\site-packages\numpy\lib\function_base.py:3821: RuntimeWarning: Invalid value encountered in percentile
  interpolation=interpolation)
c:\program files\python36\lib\site-packages\snf\compute.py:286: RuntimeWarning: invalid value encountered in less
  Wk[Wk < np.percentile(Wk, cutoff, axis=1, keepdims=True)] = 0


In [56]:
fused_network.shape

(548, 548)

In [11]:
fused_network

array([[5.57149656e-01, 4.45961825e-03, 4.31131465e-03, ...,
        1.30417738e-04, 1.11812794e-04, 1.71489830e-04],
       [4.45961825e-03, 5.57491211e-01, 5.18360724e-03, ...,
        1.33297048e-04, 1.12474158e-04, 1.79473577e-04],
       [4.31131465e-03, 5.18360724e-03, 5.57005640e-01, ...,
        1.28992762e-04, 1.07519663e-04, 1.77492231e-04],
       ...,
       [1.30417738e-04, 1.33297048e-04, 1.28992762e-04, ...,
        5.54824831e-01, 2.92642775e-03, 3.29185955e-03],
       [1.11812794e-04, 1.12474158e-04, 1.07519663e-04, ...,
        2.92642775e-03, 5.55344505e-01, 3.60456328e-03],
       [1.71489830e-04, 1.79473577e-04, 1.77492231e-04, ...,
        3.29185955e-03, 3.60456328e-03, 5.56986518e-01]])

In [12]:
digits.data

[array([[0.06588, 0.19731, 0.10383, ..., 0.39437, 0.04997, 0.34487],
        [0.04914, 0.17597, 0.10551, ..., 0.44528, 0.08398, 0.35409],
        [0.03417, 0.22765, 0.10877, ..., 0.44503, 0.07123, 0.26146],
        ...,
        [0.20397, 0.63796, 0.2894 , ..., 0.44367, 0.26406, 0.51523],
        [0.14686, 0.50432, 0.31241, ..., 0.44339, 0.07831, 0.43733],
        [0.19815, 0.4815 , 0.45344, ..., 0.42721, 0.13237, 0.30224]]),
 array([[0., 3., 4., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 2., 1., 0.],
        ...,
        [0., 1., 3., ..., 4., 4., 2.],
        [0., 0., 3., ..., 4., 4., 3.],
        [0., 0., 1., ..., 0., 0., 0.]]),
 array([[ 98., 236., 531., ...,  15.,  12.,  13.],
        [121., 193., 607., ...,  13.,  15.,  11.],
        [115., 141., 590., ...,  14.,  13.,   6.],
        ...,
        [265., 537., 776., ...,   7.,  11.,  17.],
        [261., 387., 712., ...,  12.,  12.,  17.],
        [315., 449., 734., ...,  12.,  10.,  13.]]),
 

['0',
 '0.217391304',
 '0.460869565',
 '0.339130435',
 '0.660869565',
 '0.47826087',
 '0.660869565.1',
 '0.643478261',
 '0.347826087',
 '0.843478261',
 '0.208695652',
 '0.252173913',
 '0.869565217',
 '0.382608696',
 '0.182608696',
 '0.347826087.1',
 '0.730434783',
 '0.634782609',
 '0.669565217',
 '0.895652174',
 '0.408695652',
 '0.260869565',
 '0.095652174',
 '0.617391304',
 '0.339130435.1',
 '0.556521739',
 '0.930434783',
 '0.826086957',
 '0.852173913',
 '0.443478261',
 '0.843478261.1',
 '0.426086957',
 '0.095652174.1',
 '0.582608696',
 '0.460869565.1',
 '0.765217391',
 '0.747826087',
 '0.660869565.2',
 '0.252173913.1',
 '0.460869565.2',
 '0.686956522',
 '0.913043478',
 '0.565217391',
 '0.6',
 '0.495652174',
 '0.782608696',
 '0.434782609',
 '0.782608696.1',
 '0.747826087.1',
 '0.486956522',
 '0.269565217',
 '0.791304348',
 '0.843478261.2',
 '0.765217391.1',
 '0.147826087',
 '0.565217391.1',
 '0.782608696.2',
 '0.72173913',
 '0.530434783',
 '0.72173913.1',
 '0.634782609.1',
 '0.4608695